### PR TITLE
Add typescript

### LINKED ISSUE #52: Add Typescript
Add typescript to project.

### PR DESCRIPTION
**Pull request by ayrbox**
Resolve #52

### CODE REVIEW

**Comment by JesseRWeigel** [comment]
Looks like there are some merge conflicts. Can you resolve these or do you need me to take a look?

**Comment by ayrbox** [comment]
@JesseRWeigel 
I see all js file being marked as conflicts. All files had been modified to typescript and its been rebased from main. Not sure whey its occuring. Any idea :thinking: ?

**Comment by ayrbox** [comment]
I think, I found the issue. Let me try to fix it.

**Comment by ayrbox** [comment]
@JesseRWeigel 
my bad, there are too many conflicts to fix. So I will close this PR and raise new one without conflicts.

**Pull request closed without merging**
